export const GET_CURRENCY_EXCHANGE  = 'GET_CURRENCY_EXCHANGE';
export const SET_VOLUME = 'SET_VOLUME';
export const GET_CURRENCY_INFO_FOR_CALC = 'GET_CURRENCY_INFO_FOR_CALC';
export const SET_CURRENCY_WISH = 'SET_CURRENCY_WISH';
